# to configure the lemp on the remote server

- name: myplay1
  hosts: webserver
  become: true
  tasks:
   - name: install nginx
     apt:
      name: nginx
      state: present
   - name: start nginx service
     service:
      name: nginx
      state: started
   - name: install php
     apt:
      name: php
      state: present
   - name: update apt
     shell: 'apt update'
   - name: install php8.3-fpm
     apt:
      name: php8.3-fpm
      state: present
   - name: start php-fpm service
  service:
      name: php8.3-fpm
      state: started
   - name: install mysql
     apt:
      name: mariadb-server
      state: present
   - name: start mysql service
     service:
      name: mariadb
      state: started
   - name: restart nginx service
     service:
      name: nginx
      state: restarted
   - name: restart php-fpm service
     service:
      name: php8.3-fpm
      state: restarted
   - name: restart mysql service
     service:
      name: mariadb
      state: restarted
