# on ammazon linux
- name: secret
  hosts: myserver
  become: yes
  vars_files:
    - mypass.txt
  tasks:
    - name: update yum
      yum: name='*' state=latest
    - name: install pip
      shell: "yum install python3-pip"
    - name: install Python MySQL Module
      command: "pip install PyMySQL"
    - name: install mariadb
      yum:
        name: mariadb105-server
        state: present
    - name: starting mariadb
      service:
        name: mariadb
        state: started
 
    - name: login mysql
      mysql_user:
        name: "{{ username }}"
        password: "{{ password }}"
        login_unix_socket: /var/lib/mysql/mysql.sock
        check_implicit_admin: yes
        update_password: always
        state: present



# create the mypass.txt for password and username
 
mypass.txt
user: root
password: Pass@123
 

#> to run the 
ansible-vault encrypt mypass.txt

